Models/OwnerViewModels/EditAdmin.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GlobalEvent.Models.OwnerViewModels
{
	public class EditAdmin
	{
		[Required]
		[RegularExpression(@"^[0-9a-zA-z]+@[0-9a-zA-z]+.[a-zA-z]+$", ErrorMessage = "Not a valid email.")]
		[Display(Name = "Email")]
		public string Email { get; set; }

		[StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
		[DataType(DataType.Password)]
		public string Password { get; set; }

		[DataType(DataType.Password)]
		[Display(Name = "Confirm password")]
		[Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
		public string ConfirmPassword { get; set; }
		public string Id { get; set; }

		[Required]
		[Display(Name = "First Name")]
		public string FirstName { get; set; }

		[Required]
		[Display(Name = "Last Name")]
		public string LastName { get; set; }

		[Required]
		// Determines the access level for the user: owner, manager, admin
		// Doesn't affect the actual level
		public string Level { get; set; }

		public List<SelectListItem> Levels { get; set; }


		public void CopyValues(ApplicationUser u)
		{
			this.FirstName = u.FirstName;
			this.LastName = u.LastName;
			this.Level = u.Level;
			this.Email = u.Email;
			this.Id = u.Id;

		}

        public EditAdmin()
		{
			this.Levels = new List<SelectListItem> {
                new SelectListItem { Value = "Manager", Text = "Manager" },
                new SelectListItem { Value = "Admin", Text = "Admin" }
            };
		}
	}
}

Models/OwnerViewModels/Event.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using GlobalEvent.Data;
using GlobalEvent.Models.AdminViewModels;
using GlobalEvent.Models.EBViewModels;
using GlobalEvent.Models.VisitorViewModels;
using Microsoft.EntityFrameworkCore;

namespace GlobalEvent.Models.OwnerViewModels
{
	public class Event
	{
		public int ID { get; set; }
        
		[Required]
		[Display(Name = "Name of the Event")]
		public string Name { get; set; }

		[Display(Name = "Active")]
		public bool Status { get; set; } // on/off
		public bool Archived { get; set; }

		[Required]
		[Display(Name = "Begins on")]
		public string DateStart { get; set; }

		[Required]
		[Display(Name = "Begins at")]
		public string TimeStart { get; set; }

		[Required]
		[Display(Name = "Ends on")]
		public string DateEnd { get; set; }
		
		[Required]
		[Display(Name = "Ends at")]
		public string TimeEnd { get; set; }
		public List<Visitor> Visitors { get; set; }
		public List<Ticket> Tickets { get; set; }	//types
		
		[Required]
		[Display(Name = "Eventbrite's Token")]
		public string HttpBase { get; set; } // coonection link for the source

		[Required]
		[Display(Name = "Event's Eventbrite #/ID")]
		public string EventbriteID { get; set; } // coonection link for the source

		[Required]
		[DataType(DataType.Url)]
		[Display(Name = "Event's page on Eventbrite")]
		public string TicketLink { get; set; } // link to ticket purchase page

		public int TicketsSold { get; set; }
		
		[DataType(DataType.Currency)]
		[Display(Name = "Revenue Plan, $ (optional)")]
		[DisplayFormat(DataFormatString = "{0:C}")]
		public decimal RevPlan { get; set; } // revenue planed

		[DataType(DataType.Currency)]
		[Display(Name = "Revenue Fact, $")]
		[DisplayFormat(DataFormatString = "{0:C}", ApplyFormatInEditMode = true)]
		public decimal RevFact { get; set; } // revenue fact

		[Display(Name = "Free Event")]
		public bool Free { get; set; } // if the evenT is free
		public List<Product> Products { get; set; }
        public List<Order> Orders { get; set; }     //all orders
		public List<VType> Types { get; set; } // types of visitors stuff/guests/speakers
		
		[Required]
		[StringLength(1000, MinimumLength = 10)]
		[Display(Name = "Event's description (visible to public).")]
		public string Description { get; set; }

		public Event()
		{
            this.Tickets = new List<Ticket>();
            this.Visitors = new List<Visitor>();
            this.Orders = new List<Order>();
			this.Products = new List<Product>();
			this.TicketsSold = 0;
			this.RevFact = 0;
			this.RevPlan = 0;
			this.Free = false;
			this.Types = new List<VType>();
			this.Archived = false;
		}

		public static async Task Update (ApplicationDbContext _db, int ID)
		{
			// Update orders
            await Order.OrderUpdate(_db, ID);
			await Ticket_Classes.UpdateEB(_db, ID);
			
			Event e = await _db.Events
				.Include(x => x.Tickets)
				.Include(x => x.Types)
                .Include(x => x.Orders)
				.Include(X => X.Visitors)
				.FirstOrDefaultAsync(x => x.ID == ID);

			e.RevFact = 0;
			// Tickets
			foreach (Ticket t in e.Tickets)
			{
				t.Sold = e.Orders
					.Where(x => x.TicketType == t.Type).Sum(x => x.Amount);
				t.CheckIned = e.Visitors
					.Where(x => x.TicketType == t.Type && x.CheckIned).Count();
				t.Registered = e.Visitors
					.Where(x => x.TicketType == t.Type && x.Registered).Count();
				e.RevFact += t.Sold * t.Price;
			}

			e.TicketsSold = e.Orders.Sum(x => x.Amount);

			//VTypes
			foreach (VType v in e.Types)
			{
				v.CheckIned = e.Visitors
					.Where(x => x.Type == v.Name && x.CheckIned && !x.Deleted).Count();
				v.Registered = e.Visitors
					.Where(x => x.Type == v.Name && x.Registered && !x.Deleted).Count();
			}

			_db.Events.Update(e);
			await _db.SaveChangesAsync();
		}

		public List<Request> GetAllRequests()
		{
			// select all requests for current event
            var list = new List<Request>();
			foreach (var item in this.Visitors)
			{
				list.AddRange(item.Requests);
			}

			return list;
		}

		public async Task<Event> CopyValues (ApplicationDbContext _db)
		{
			Event eOld = await _db.Events.FirstOrDefaultAsync(x => x.ID == this.ID);
            
            // updating the event's data
            eOld.Name = this.Name;
            eOld.DateStart = this.DateStart;
            eOld.DateEnd = this.DateEnd;
            eOld.TimeStart = this.TimeStart;
            eOld.TimeEnd = this.TimeEnd;
            eOld.Free = this.Free;
            eOld.RevPlan = this.RevPlan;
            eOld.Archived = this.Archived;
            eOld.HttpBase = this.HttpBase;
            eOld.EventbriteID = this.EventbriteID;
            eOld.TicketLink = this.TicketLink;
            eOld.Description = this.Description; 
            
			return eOld;
		}	
	}
}

Controllers/OwnerController.cs
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using GlobalEvent.Data;
using GlobalEvent.Models.OwnerViewModels;
using GlobalEvent.Models.VisitorViewModels;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;
using GlobalEvent.Models;
using System.Reflection;
using System.Security.Claims;
using GlobalEvent.Models.AdminViewModels;
using Microsoft.AspNetCore.Http;

namespace GlobalEvent.Controllers
{
	[Authorize]
    public class OwnerController : Controller
    {
		private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;
        private string _id;

		public OwnerController (UserManager<ApplicationUser> userManager, ApplicationDbContext context, IHttpContextAccessor http)
        {
            _db = context;
            _userManager = userManager;
            _id = _userManager.GetUserId(http.HttpContext.User);
        }

        //
        // GET: Owner/Index
        [HttpGet]
        [Authorize(Policy="Owner's Menu")]
        public async Task<IActionResult> Index(string message = null)
        {
            // get all unfinished todos 
            ViewBag.Todos = _db.ToDos
                .Where(x => !x.Done)
                .OrderBy(x => x.Deadline)
                .ToList();
                
            ViewBag.Message = message;
            ViewBag.EventList = await ToDo.GenerateEventList(_db);

            return View();
        }

        //
        // GET: Owner/Dashboard
        [HttpGet]
        [Authorize(Policy="Owner's Dashboard")]
        public async Task <IActionResult> Dashboard ()
        {
            Event active = await _db.Events
                .Include(x => x.Tickets)
                .Include(x => x.Visitors)
                    .ThenInclude(x => x.Requests)
                .Include(x => x.Products)
                .FirstOrDefaultAsync(x => x.Status);
            
            if (active == null)
            {
                 return View();
            }

            // update tickets and orders data
            await Event.Update(_db, active.ID);
            ViewBag.CheckIned = active.Visitors.Where(x => x.CheckIned).Count();
            ViewBag.Registered = active.Visitors.Where(x => x.Registered).Count();
            
            // select all requests for current event
            ViewBag.Requests = new List<Request>();
            ViewBag.NotSeen = 0;
            ViewBag.Important = 0;
            foreach (var item in active.Visitors)
            {
                ViewBag.Requests.AddRange(item.Requests);
                ViewBag.NotSeen += item.Requests.Where(x => !x.SeenByAdmin).Count();
                ViewBag.Important += item.Requests.Where(x => x.Important).Count();
            }
            
            // get all blocked visitors
            ViewBag.Blocked = await _db.Visitors
                .Where(x => x.Blocked && x.EID == active.ID).ToListAsync();

            // get all deleted visitors
            ViewBag.Deleted = await _db.Visitors
                .Where(x => x.Deleted && x.EID == active.ID).ToListAsync();

            // total tickets amount
            ViewBag.AllTickets = 0;
            active.Tickets.ForEach(t => ViewBag.AllTickets += t.Limit);

            return View(active);
        }

        //
        // GET: Owner/Events
        [HttpGet]
        [Authorize(Policy="Events Viewer")]
        public async Task<IActionResult> Events (string message = null)
        {
            // get active event
            ViewBag.Active = await _db.Events.FirstOrDefaultAsync(x => x.Status);
            
            // get all upcoming events
            ViewBag.Future = await _db.Events
                .Where(x => !x.Status && !x.Archived)
                .ToListAsync(); 

            // get all archived events
            ViewBag.Archived = await _db.Events
                .Where(x => x.Archived)
                .ToListAsync();

            ViewBag.Message = message;
            return View();
        }

        //
        // GET: Owner/CreateEvent
        [HttpGet]
        [Authorize(Policy="Event Creator")]
        public IActionResult CreateEvent ()
        {
            return View();
        }

        //
        // POST: Owner/CreateEvent
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        [Authorize(Policy="Event Creator")]
        public async Task<IActionResult> CreateEvent (Event e)
        {
            if (ModelState.IsValid)
            {
                _db.Events.Add(e);
                
                // Log for admin
                await _db.Logs.AddAsync(await Log.New("Event", $"Event: {e.Name}, was created", _id, _db));

                return RedirectToAction("Events", new { message = "The Event was successfully created."});
            }

            return RedirectToAction("Events", new { message = "Event wasn't created. Something went wrong. Please try again."});
        }

        //
        // GET: Owner/EditEvent
        [HttpGet]
        [Authorize(Policy="Event Editor")]
        public async Task<IActionResult> EditEvent (int? ID)
        {
            if (ID == null) 
            {
                return RedirectToAction("Events");
            }

            Event edit = await _db.Events.SingleOrDefaultAsync(x => x.ID == ID);
            return View(edit);
        }

        //
        // POST: Owner/EditEvent
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        [Authorize(Policy="Event Editor")]
        public async Task<IActionResult> EditEvent (Event model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Events", new { message = "Something went wrong. Please try again."});
            }
            
            Event eventToEdit = await model.CopyValues(_db);
            
            // check if there is any active event in db
            if (!eventToEdit.Status 
                && model.Status 
                && await _db.Events.AnyAsync(x => x.Status))
            {
                eventToEdit.Status = false;
                ViewBag.Message = "One of the Events is currently ACTIVE. And only 1 event can be ACTIVE at a time. You have to change it's status in order to make any other event ACTIVE. All other changes were saved.";
            }
            else
            {
                // change status if no active event found
                eventToEdit.Status = model.Status;
            }
            
            _db.Events.Update(eventToEdit);        
            
            // log for admin
            await _db.Logs.AddAsync(await Log.New("Event", $"Event: {eventToEdit.Name}, was EDITED", _id, _db));

            return RedirectToAction("ViewEvent", new { ID = eventToEdit.ID, message = ViewBag.Message });
        }

        //
        // GET: Owner/ViewEvent
        [HttpGet]
        [Authorize(Policy="Event Viewer")]
		public async Task<IActionResult> ViewEvent(int? ID, string message = null)
		{
			if (ID == null) 
            {
                return RedirectToAction("Events");
            }

			// get event by ID
			Event eventToView = await _db.Events
				.Include(x => x.Tickets)
				.Include(x => x.Types)
				.Include(x => x.Products)
                .Include(x => x.Orders)
				.SingleOrDefaultAsync(x => x.ID == ID);
            
            // Update orders and tickets
            await Order.OrderUpdate(_db, eventToView.ID);
            await Event.Update(_db, eventToView.ID);

            // update attendance
            ViewBag.CheckIned = eventToView.Visitors.Where(x => x.CheckIned).Count();
            ViewBag.Registered = eventToView.Visitors.Where(x => x.Registered).Count();
            
            // total amount of tickets
            ViewBag.AllTickets = 0;
            eventToView.Tickets.ForEach(t => ViewBag.AllTickets += t.Limit);

            ViewBag.Message = message;

			return View(eventToView);
		}

        //
        // GET: Owner/DeleteEvent
        [HttpGet]
        [Authorize(Policy="Event Killer")]
        public async Task<IActionResult> DeleteEvent (int? ID)
        {
            if (ID == null) 
            {
                return RedirectToAction("Events");
            }
            Event eventToDelete = await _db.Events.SingleOrDefaultAsync(x => x.ID == ID);

            return View(eventToDelete);
        }

        //
        // GET: Owner/DeleteEventOk
        [HttpGet]
        [Authorize(Policy="Event Killer")]
        public async Task<IActionResult> DeleteEventOk (int? ID)
        {
            if (ID == null) 
            {
                return RedirectToAction("Events");
            }

            Event eventToDelete = await _db.Events.FirstOrDefaultAsync(x => x.ID == ID);
            _db.Events.Remove(eventToDelete);
            
            // log for admin
            await _db.Logs.AddAsync(await Log.New("Event", $"Event: {eventToDelete.Name}, was DELETED", _id, _db));

            return RedirectToAction("Events");
        }

        //
        // GET: Owner/Admins
        [HttpGet]
        [Authorize(Policy="Admins Viewer")]
        public async Task<IActionResult> Admins ()
        {
            // get all users/admins
            ViewBag.Admins = await _db.Users.ToListAsync();
            
            return View();
        }

        //
        // GET: Owner/Attention
        [HttpGet]
        [Authorize(Policy = "Owner's Menu")]
        public async Task<IActionResult> Attention ()
        {
            // get all unsolved and unseen requests
            ViewBag.Requests = await _db.Requests
                .Where(x => !x.Solved && !x.SeenByAdmin)
                .OrderBy(x => x.Important)
                    .ThenBy(x => x.Date)
                    .ThenBy(x => x.Time)
                .ToListAsync();

            // get all unsolved and unassigned issues
            ViewBag.Issues = await _db.Issues

Views/Owner/Attention.cshtml
<h1> Require Attention</h1>

@if(ViewBag.Message != null) {
<div id="tog" class="f-attention">@ViewBag.Message <br/>
	<a class="btn mybtn-sm-red tog inline m5-0-5-0" data-id="tog">OK</a>
</div>
} 

<!-- buttons -->
<div class="text-center">
	<a asp-action="Attention" asp-controller="Owner" class="btn mybtn bgBase">Refresh</a>
</div>
<!-- end of buttons -->

<!-- VISITOR"S Requests -->
<div class="row text-center m20-0-20-0 tog" data-id="requests">
    <h2> Visitor's Requests / Complaints</h2>
</div>

@if(ViewBag.Requests != null && ViewBag.Requests.Count != 0)
{
<table class="table table-hover eye" id="requests">
	<thead>
		<tr style="border-bottom: 2px solid gray;">
			<th>ID</th>
			<th>Time</th>
			<th>Date</th>
			<th style="width: 40%;">Description</th>
			<th>Admin</th>
			<th>Important</th>
			<th>Seen</th>
			<th>Solved</th>
			<th></th>
		</tr>
	</thead>
	<tbody>

	@foreach(var r in ViewBag.Requests)
	{	
	<tr>
		<td>@r.ID</td>
		<td>@r.Time</td>
		<td>@r.Date</td>
		<td style="width: 40%;">@r.Description</td>
		<td>@r.AdminName</td>
		<td class="text-center">
			<div class="bulp @(r.Important ? "bgRed" : "bgBase")"></div>
		</td>
		<td>
			<div class="bulp @(r.SeenByAdmin ? "bgBase" : "bgRed")"></div>
		</td>
		<td>
			<div class="bulp @(r.Solved ? "bgBase" : "bgRed")"></div>
		</td>
		<td style="width: auto; text-align: right;">
			<div class="dropdown">
				<button class="btn mybtn-sm-actions bgBro" type="button" data-toggle="dropdown">Actions &nbsp &#x25BC;</button>
				<ul class="dropdown-menu dropdown-menu-right">
					<li><a asp-action="ViewVisitor" asp-controller="Admin" asp-route-ID="@r.VID">View Info</a></li>
					<li><a asp-action="Edit" asp-controller="Request" asp-route-ID="@r.ID">Edit</a></li>
					<li><a asp-action="Status" asp-controller="Request" asp-route-ID="@r.ID" asp-route-Name="SOLVED">Change Solved </a></li>
					<li><a asp-action="Status" asp-controller="Request" asp-route-ID="@r.ID" asp-route-Name="IMPORTANT">Change Importance</a></li>
					<li><a asp-action="Status" asp-controller="Request" asp-route-ID="@r.ID" asp-route-Name="SEEN">Change Seen</a></li>
					<li><a asp-action="Delete" asp-controller="Request" asp-route-ID="@r.ID">Delete</a></li>
				</ul>
			</div>		
		</td>
	</tr>
	}
	</tbody>
</table>
}
else
{
<div class="text-center">
	No requests have been created yet.
</div>
}


<!-- VISITOR'S NOTES -->
<div class="row text-center m20-0-20-0 tog" data-id="notes">
    <h2> Visitor's Notes</h2>
</div>

@if(ViewBag.Notes != null && ViewBag.Notes.Count != 0)
{
<table class="table table-hover eye" id="notes">
	<thead>
		<tr style="border-bottom: 2px solid gray;">
			<th>ID</th>
			<th>Time</th>
			<th>Date</th>
			<th style="width: 40%;">Description</th>
			<th>Admin</th>
			<th>Important</th>
			<th>Seen</th>
			<th></th>
		</tr>
	</thead>
	<tbody>

	@foreach(var n in ViewBag.Notes)
	{	
		<tr>
			<td>@n.ID</td>
			<td>@n.Time</td>
			<td>@n.Date</td>
			<td style="width: 40%;">@n.Description</td>
			<td>@n.AdminName</td>
			<td class="text-center">
				<div class="bulp @(n.Important ? "bgRed" : "bgBase")"></div>
			</td>
			<td>
				<div class="bulp @(n.SeenByAdmin ? "bgBase" : "bgRed")"></div>
			</td>
			<td style="width: auto; text-align: right;">	
				<div class="dropdown">
					<button class="btn mybtn-sm-actions bgBro" type="button" data-toggle="dropdown">Actions &nbsp &#x25BC;</button>
					<ul class="dropdown-menu dropdown-menu-right">
						<li><a asp-action="ViewVisitor" asp-controller="Admin" asp-route-ID="@n.VID">View Info</a></li>
						<li><a asp-action="Edit" asp-controller="Note" asp-route-ID="@n.ID">Edit</a></li>
						<li><a asp-action="Status" asp-controller="Note" asp-route-ID="@n.ID" asp-route-Name="IMPORTANT">Change Importance</a></li>
						<li><a asp-action="Status" asp-controller="Note" asp-route-ID="@n.ID" asp-route-Name="SEEN">Change Seen</a></li>
						<li><a asp-action="Delete" asp-controller="Note" asp-route-ID="@n.ID">Delete</a></li>
					</ul>
				</div>		
			</td>
		</tr>
	}
	</tbody>
</table>
}
else
{
<div class="text-center">
	No notes have been created yet.
</div>
}


<!-- ALL ISSUES -->
<div class="row text-center m20-0-20-0 tog" data-id="issues">
	<h2> ALL ISSUES </h2>
</div>

@if(ViewBag.Issues != null && ViewBag.Issues.Count != 0) {
<table class="table table-hover eye" id="issues">
	<thead>
		<tr style="border-bottom: 2px solid gray;">
			<th>ID</th>
			<th>Time</th>
			<th>Date</th>
			<th>Type</th>
			<th style="width: 40%;">Description</th>
			<th>Due Date</th>
			<th>Admin</th>
			<th>Assigned</th>
			<th>Solved</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach(var i in ViewBag.Issues) {
		<tr>
			<td>@i.ID</td>
			<td>@i.Time</td>
			<td>@i.Date</td>
			<td>@i.Type</td>
			<td style="width: 40%;">@i.Description</td>
			<td>@i.ExpectedToBeSolved</td>
			<td>@i.AdminName</td>
			<td class="text-center">
				<div class="bulp @(i.Assigned ? " bgBase " : "bgRed ")"></div>
			</td>
			<td class="text-center">
				<div class="bulp @(i.Solved ? " bgBase " : "bgRed ")"></div>
			</td>
			<td style="width: auto; text-align: right;">	
				<div class="dropdown">
					<button class="btn mybtn-sm-actions bgBro" type="button" data-toggle="dropdown">Actions &nbsp &#x25BC;</button>
					<ul class="dropdown-menu dropdown-menu-right">
						<li><a asp-action="Edit" asp-controller="Issue" asp-route-ID="@i.ID">Edit</a></li>
						<li><a asp-action="Status" asp-controller="Issue" asp-route-ID="@i.ID" asp-route-Name="Solved">Change Solved</a></li>
						<li><a asp-action="Status" asp-controller="Issue" asp-route-ID="@i.ID" asp-route-Name="Assigned">Change Assigned</a></li>
						<li><a asp-action="Delete" asp-controller="Issue" asp-route-ID="@i.ID">Delete</a></li>
					</ul>
				</div>		
			</td>
		</tr>
		}
	</tbody>
</table>
} 
else 
{
<div class="text-center">
	No issues have been created yet.
</div>
}

Views/Owner/ChangeClaims.cshtml
@model Claims
@using System.Reflection
@{
	bool check = false;
	string name = " ";
}
<h1> Admin's access</h1>
<h3> @ViewBag.AdminName </h3>

<form asp-action="ChangeClaims" asp-controller="Owner" asp-route-ID="@ViewBag.AID" autocomplete="off">

@foreach(var c in ViewBag.Properties)
{
	check = c.Name.StartsWith(name) ? true : false;
	@if(!check)
	{	
		name = c.Name.Substring(0, c.Name.IndexOf("C"));
		<div class="events-number-container" style="border-bottom: 1px solid #3cb371;">
			<span class="events-number bgBase">@name</span>
		</div>
		check = true;
	}
	@if(c.Name.StartsWith(name))
	{
		<div class="form-group inline" style="margin-right: 30px;">
			<label class="control-label" for="@c.Name">
				@(Regex.Replace(c.Name.Replace(name, ""), @"(\B[A-Z]+?(?=[A-Z][^A-Z])|\B[A-Z]+?(?=[^A-Z]))", " $1"))
			</label>&nbsp
			<span class="true-false" data-id="@c.Name"></span>
			
			<input class="eye" @(c.GetValue(Model, null) == false ? "" : "checked") data-val="true" data-val-required="The @c.Name Event field is required." id="@c.Name" name="@c.Name" type="checkbox" value="true" />
		</div>
	}
}
	<div class="text-center form-group">
		<button type="submit" class="btn mybtn bgBase">Save</button>
		<a asp-action="EditAdmin" asp-controller="Owner" asp-route-ID="@ViewBag.AID" class="btn mybtn bgRed">Cancel</a>
	</div>
</form>

Views/Owner/DeleteEvent.cshtml
@model Event

<h1>DELETE EVENT</h1>

@if (Model.Status)
{
	<div class="f-attention">You can NOT delete an Active event. Please, make it inactive first.
	</div>
	<div class="text-center">
		<a asp-action="Events" asp-controller="Owner" class="btn mybtn bgBase">BACK</a>
	</div>
}
else
{
	<div class="f-info">You are going to delete the event:<br /> @Model.Name</div>

	<div class="text-center">
		<a asp-action="Events" asp-controller="Owner">
			<button type="button" style="width: 80px;" class="btn mybtn bgBase">CANCEL</button>
		</a>
		<a asp-action="DeleteEventOk" asp-controller="Owner" asp-route-id="@Model.ID">
			<button type="button" style="width: 80px;" class="btn mybtn bgRed">DELETE</button>
		</a>
	</div>
}

Views/Owner/Events.cshtml
<h1>All Events</h1> 
@{
	var future = ViewBag.Future;
	var archived = ViewBag.Archived;
}
@if(ViewBag.Message != null)
{
	<div id="tog" class="f-info">@ViewBag.Message
        <a class="btn mybtn-sm-bro tog inline m5-0-5-0" data-id="tog">OK</a>
    </div>
}

<div class="text-center">
	@if(await AuthorizationService.AuthorizeAsync(User, "Event Creator"))
	{
	<a asp-action="CreateEvent" class="btn mybtn bgBase">ADD</a>
	}
	<a asp-action="Index" class="btn mybtn bgBro">BACK</a>
</div>
	<br />

@if (ViewBag.Active == null && future.Count == 0 && archived.Count == 0)
{
	<div class="f-info">You don't have any Events yet.</div>
}
else
{
	
	@if (ViewBag.Active != null)
	{
		<div class="events-number-container" style="border-bottom: 1px solid #3cb371;">
            <span class="events-number bgBase">ACTIVE</span>
        </div>
		<a asp-action="ViewEvent" asp-route-id="@ViewBag.Active.ID" class="btn btn-events bgBase">
            @ViewBag.Active.Name : @ViewBag.Active.DateStart / @ViewBag.Active.DateEnd
        </a><br />
	}

	@if (future.Count != 0)
	{
		<br />
		<div class="events-number-container">
            <span class="events-number bgBro">FUTURE</span>
        </div>
		@foreach (Event e in future)
		{
			<a asp-action="ViewEvent" asp-route-id="@e.ID" class="btn btn-events bgBro">
				@e.Name : @e.DateStart / @e.DateEnd
			</a><br />
		}
	}

	@if (archived.Count != 0)
	{
		<br />
		<div class="events-number-container" style="border-bottom: 1px solid gray">
            <span class="events-number bgGray">ARCHIVED</span>
        </div>
		@foreach (Event e in archived)
		{
			<a asp-action="ViewEvent" asp-route-id="@e.ID" class="btn btn-events bgGray">
				@e.Name : @e.DateStart / @e.DateEnd
			</a><br />
		}
	}
}